### PR TITLE
Backport https://review.openstack.org/#/c/108272/6

### PR DESCRIPTION
**Pull request by kevinbringard**
Funtionally tested in SVL3 by manully creating the lease-init-script.
I couldn't test the setup.cfg stuff due to not building packages, but
it should work the same way.

### CODE REVIEW

**Comment by alop** [comment]
I think you need to include the upstream review in the commit message

**Comment by yeungp** [comment]
Unit test for test_linux_dhcp.py failed
FAIL: neutron.tests.unit.test_linux_dhcp.TestDnsmasq.test_output_opts_file_no_neutron_router_on_subnet
FAIL: neutron.tests.unit.test_linux_dhcp.TestDnsmasq.test_release_lease

Otherwise +1

**Comment by yeungp** [comment]
Where is neutron-dhcp-agent-dnsmasq-lease-init?

Need the following line in setup.cfg under "scripts =" for this to work in devstack
bin/neutron-dhcp-agent-dnsmasq-lease-init

**Comment by kevinbringard** [comment]
@yeungp It should be there under console_scripts:

86     neutron-dhcp-agent-dnsmasq-lease-init = neutron.agent.linux.dhcp:Dnsmasq.lease_init

I'll look into those other 2 test failures. This is a direct backport, so I'm guessing there's something funky happening.

**Comment by kevinbringard** [comment]
@yeungp this failures happen without my changes (on the base cis-havana-staging branch). I'm thinking the failures are unrelated to my changes.

**Comment by kevinbringard** [comment]
Going to create a new PR as this should be merged into cis-havana. Staging is no longer in use.

**Pull request closed without merging**
